version: "1.0"
info:
  model: int-scaffold
packages:
- name: CriticalIssueProject
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: main
- name: TPPWithVar
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: "2.0"
services:
- serviceName: project.criticalissue.integrations:DAF1
  packages:
  - name: CriticalIssueProject
    version: 2.0.0
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 12.1.0.0.1202
