info:
  model: int-scaffold
packages:
- gitBranch: main
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: CriticalIssueProject
- gitBranch: '1.0'
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: TPPWithVar
services:
- packages:
  - name: CriticalIssueProject
    version: 2.0.0
  serviceName: project.criticalissue.integrations:DAF1
- packages:
  - name: WmPublic
    version: 12.1.0.0.1202
  serviceName: pub.date:currentNanoTime
version: '1.0'
